apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-frontend
  namespace: library
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-frontend
  template:
    metadata:
      labels:
        app: library-frontend
    spec:
      containers:
      - name: library-frontend
        image: muskan390/library-frontend:latest
        ports:
        - containerPort: 3000
