apiVersion: v1
kind: Service
metadata:
  name: library-frontend-service
  namespace: library
spec:
  type: NodePort
  selector:
    app: library-frontend
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30007
