name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Start Minikube
      run: |
        echo "Starting Minikube..."
        minikube start --driver=docker

    - name: Configure Docker to use Minikube's daemon
      run: |
        echo "Setting Docker env to Minikube..."
        eval $(minikube docker-env)

    - name: Build Docker images
      run: |
        echo "Building backend and frontend Docker images..."
        docker build -t muskan390/library-backend:latest ./app/backend
        docker build -t muskan390/library-frontend:latest ./app/frontend

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker images to Docker Hub
      run: |
        docker push muskan390/library-backend:latest
        docker push muskan390/library-frontend:latest

    - name: Use Minikube context
      run: kubectl config use-context minikube

    - name: Deploy to Minikube
      run: |
        echo "Deploying to Minikube cluster..."
        kubectl apply -f k8s/secret.yaml
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend-service.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend-service.yaml

